# Generated by Django 3.2.23 on 2023-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_weapon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='slug',
        ),
    ]
